spring:
  application:
    name: ms-spring-accounts
  rabbitmq:
    host: localhost
    port: 5672

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

exchanges:
  fanout: payment