server:
  port: 8125 # Zuul's default port

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
           allowedOrigins: http://localhost:5173
           allowedMethods:
           - GET
             POST
             PUT
             DELETE
      routes:
      - id: ms-spring-listings
        uri: lb://ms-spring-listings
        predicates:
          - Path=/listings/**
        filters:
        - name: CircuitBreaker # MUST BE THIS, Provided by Resilience4J
          args:
            name: fallbackController # Because I'll have a controller called FallbackController
            fallbackUri: forward:/cache/listings
      - id: ms-spring-accounts
        uri: lb://ms-spring-accounts
        predicates:
          - Path=/accounts/**
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka